# Metadata
sonar.projectKey=ThibaultPouch59200_SCHT_c5518178-cc11-46be-8da4-45224ecbacc9
sonar.projectName=SCHT

# Source information
sonar.sources=frontend/src,backend/src
sonar.sourceEncoding=UTF-8
sonar.inclusions=**/*.ts,**/*.tsx,**/*.vue
sonar.exclusions=**/node_modules/**,**/coverage/**,**/public/**,**/__tests__/**

# Tests
sonar.tests=backend/src/__tests__
sonar.test.inclusions=**/*.test.ts
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info
